CREATE TABLE micro_tran.ORDER_TA (ID INT PRIMARY KEY AUTO_INCREMENT,  CUSTOMERID INT, COMMITDATE INT(15), STATUS INT);
CREATE TABLE micro_tran.PRODUCT_TA (PRODUCTID INT PRIMARY KEY AUTO_INCREMENT,  NAME VARCHAR(255));
CREATE TABLE micro_tran.ORDER_PRODUCT_TA (PRODUCTID INT, ORDERID INT);
CREATE TABLE micro_tran.CUSTOMER_TA (ID INT PRIMARY KEY AUTO_INCREMENT,   NAME VARCHAR(255), FIRSTNAME VARCHAR(255), BIRTHDATE INT(12));

INSERT INTO micro_tran.ORDER_TA (COMMITDATE , STATUS) VALUES (345345345, 5);
INSERT INTO micro_tran.PRODUCT_TA(NAME  ) VALUES('Test');