CREATE TABLE ORDER_TA (ID INT PRIMARY KEY,   COMMITDATE NUMBER(15), STATUS INT);
CREATE TABLE PRODUCT_TA (PRODUCTID INT PRIMARY KEY,  NAME VARCHAR(255));
CREATE TABLE ORDER_PRODUCT_TA (PRODUCTID INT, ORDERID INT);
CREATE SEQUENCE HIBERNATE_SEQUENCE;
INSERT INTO ORDER_TA (ID,   COMMITDATE , STATUS) VALUES (1, 345345345, 5);
INSERT INTO PRODUCT_TA(PRODUCTID, NAME  ) VALUES(9999, 'Test');